import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * ProductoCard - Tarjeta de producto con efecto flip para vista cuadrícula
 * Frente: Vista resumida con imagen y datos principales
 * Reverso: Vista detallada con información de stock y acciones
 */
import { useState } from 'react';
import { getEstadoStock } from '../types/inventario';
import { Card } from './Card';
import { StockBadge, CategoriaBadge } from './Badge';
import { DollarSign, Package, RotateCcw, Edit3, AlertTriangle } from 'lucide-react';
/** Obtiene la ruta de imagen según la categoría */
const getImagenProducto = (producto) => {
    if (producto.imagen)
        return producto.imagen;
    const categoriaLower = producto.categoria.toLowerCase();
    if (categoriaLower.includes('almuerzo'))
        return '/src/assets/qr-validation-seller/productos/1.jpg';
    if (categoriaLower.includes('desayuno'))
        return '/src/assets/qr-validation-seller/productos/2.jpg';
    if (categoriaLower.includes('bebidas'))
        return '/src/assets/qr-validation-seller/productos/3.jpg';
    return '/src/assets/qr-validation-seller/productos/1.jpg';
};
export const ProductoCard = ({ producto, onEditStock, onVerDetalles, }) => {
    const [isFlipped, setIsFlipped] = useState(false);
    const estadoStock = getEstadoStock(producto.stock, producto.stockMinimo);
    const handleFlip = () => setIsFlipped(!isFlipped);
    /** Frente de la tarjeta */
    const CardFront = () => (_jsxs("div", { className: "h-full flex flex-col", children: [_jsxs("div", { className: "relative h-44 overflow-hidden rounded-t-xl", children: [_jsx("img", { src: getImagenProducto(producto), alt: producto.nombre, className: "w-full h-full object-cover" }), _jsx("div", { className: "absolute top-3 left-3", children: _jsx(CategoriaBadge, { categoria: producto.categoria }) }), estadoStock === 'stock-bajo' && (_jsx("div", { className: "absolute top-3 right-3", children: _jsxs("span", { className: "inline-flex items-center px-2 py-1 rounded-full text-xs font-semibold bg-orange-500 text-white", children: [_jsx(AlertTriangle, { className: "w-3 h-3 mr-1" }), "Stock Bajo"] }) }))] }), _jsxs("div", { className: "flex flex-col flex-grow p-4", children: [_jsx("h3", { className: "font-bold text-gray-900 text-lg mb-1 truncate", children: producto.nombre }), producto.descripcion && (_jsx("p", { className: "text-sm text-gray-500 mb-3 line-clamp-2", children: producto.descripcion })), _jsxs("div", { className: "flex items-center justify-between mb-3 pb-3 border-b border-gray-100", children: [_jsxs("div", { className: "flex items-center text-lg font-bold text-yellow-500", children: [_jsx(DollarSign, { className: "w-5 h-5" }), _jsx("span", { children: producto.precio.toLocaleString() })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Package, { className: "w-4 h-4 text-gray-400" }), _jsx("span", { className: "text-sm text-gray-600", children: "Stock:" }), _jsx("input", { type: "number", value: producto.stock, readOnly: true, className: "w-14 text-center text-sm font-semibold border border-gray-300 rounded-lg py-1 bg-gray-50" })] })] }), _jsxs("div", { className: "flex gap-2 mt-auto", children: [_jsx("button", { onClick: handleFlip, className: "flex-1 bg-white hover:bg-gray-50 text-yellow-500 border-2 border-yellow-400 py-2.5 px-3 rounded-xl text-sm font-semibold transition-all duration-200 flex items-center justify-center", children: "Ver Detalles" }), _jsxs("button", { onClick: () => onEditStock(producto.id), className: "flex-1 bg-yellow-400 hover:bg-yellow-500 text-white py-2.5 px-3 rounded-xl text-sm font-semibold transition-all duration-200 flex items-center justify-center shadow-md hover:shadow-lg", children: [_jsx(Edit3, { className: "w-4 h-4 mr-1.5" }), "Editar"] })] })] })] }));
    /** Reverso de la tarjeta */
    const CardBack = () => (_jsxs("div", { className: "h-full flex flex-col", children: [_jsxs("div", { className: "bg-gradient-to-r from-yellow-400 to-yellow-500 text-white p-4 rounded-t-xl", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsxs("div", { className: "flex-1 min-w-0 mr-2", children: [_jsx("h3", { className: "font-bold text-lg truncate", children: producto.nombre }), _jsx("p", { className: "text-sm text-yellow-100", children: producto.categoria })] }), _jsx("button", { onClick: handleFlip, className: "bg-white/20 hover:bg-white/30 backdrop-blur-sm text-white p-2 rounded-lg transition-colors duration-200 flex-shrink-0", children: _jsx(RotateCcw, { className: "w-5 h-5" }) })] }), _jsxs("div", { className: "flex items-center justify-between mt-3 pt-3 border-t border-white/20", children: [_jsx("span", { className: "text-sm text-yellow-100", children: "Precio" }), _jsxs("div", { className: "flex items-center text-2xl font-bold", children: [_jsx(DollarSign, { className: "w-6 h-6" }), _jsx("span", { children: producto.precio.toLocaleString() })] })] })] }), _jsxs("div", { className: "flex-grow overflow-y-auto p-4", children: [_jsxs("div", { className: "mb-4", children: [_jsx("h4", { className: "font-bold text-gray-900 text-sm mb-2", children: "Estado del Stock" }), _jsxs("div", { className: "bg-gray-50 rounded-lg p-3", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Estado actual" }), _jsx(StockBadge, { estado: estadoStock })] }), _jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Cantidad disponible" }), _jsxs("span", { className: "font-bold text-gray-900", children: [producto.stock, " unidades"] })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Stock m\u00EDnimo" }), _jsxs("span", { className: "font-semibold text-gray-700", children: [producto.stockMinimo, " unidades"] })] })] })] }), producto.descripcion && (_jsxs("div", { className: "mb-4", children: [_jsx("h4", { className: "font-bold text-gray-900 text-sm mb-2", children: "Descripci\u00F3n" }), _jsx("p", { className: "text-sm text-gray-600 bg-gray-50 rounded-lg p-3", children: producto.descripcion })] })), _jsxs("div", { className: "bg-yellow-50 border border-yellow-200 rounded-lg p-3", children: [_jsx("p", { className: "text-xs font-semibold text-yellow-800 mb-1", children: "\u00DAltima actualizaci\u00F3n" }), _jsx("p", { className: "text-sm text-yellow-900", children: new Date(producto.fechaActualizacion).toLocaleDateString('es-CO', {
                                    day: 'numeric',
                                    month: 'long',
                                    year: 'numeric',
                                    hour: '2-digit',
                                    minute: '2-digit'
                                }) })] })] }), _jsx("div", { className: "p-4 border-t border-gray-100", children: _jsxs("button", { onClick: () => onEditStock(producto.id), className: "w-full bg-yellow-400 hover:bg-yellow-500 text-white py-3 px-4 rounded-xl font-semibold transition-all duration-200 flex items-center justify-center shadow-md hover:shadow-lg", children: [_jsx(Edit3, { className: "w-4 h-4 mr-2" }), "Editar Stock"] }) })] }));
    return (_jsx("div", { className: "relative w-full h-[420px]", style: { perspective: '1000px' }, children: _jsxs("div", { className: `relative w-full h-full transition-transform duration-700 ease-in-out ${isFlipped ? '[transform:rotateY(180deg)]' : '[transform:rotateY(0deg)]'}`, style: { transformStyle: 'preserve-3d' }, children: [_jsx("div", { className: "absolute inset-0 w-full h-full", style: { backfaceVisibility: 'hidden' }, children: _jsx(Card, { className: "h-full hover:shadow-xl transition-shadow duration-300 border border-gray-200 overflow-hidden", children: _jsx(CardFront, {}) }) }), _jsx("div", { className: "absolute inset-0 w-full h-full", style: { backfaceVisibility: 'hidden', transform: 'rotateY(180deg)' }, children: _jsx(Card, { className: "h-full hover:shadow-xl transition-shadow duration-300 border border-gray-200 overflow-hidden", children: _jsx(CardBack, {}) }) })] }) }));
};
