import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * OrderDetailsView - Vista de resumen final antes de confirmar la compra
 * Muestra método de pago, punto de recogida y hora de entrega
 */
import { CreditCard, MapPin, Clock } from 'lucide-react';
export default function OrderDetailsView({ selectedPaymentMethod = 'Billetera', paymentDetails = '125.000', selectedPickupMethod = 'Punto de venta', pickupLocation = 'Harvies - Costado Oeste del coliseo El otoño', deliveryDate = '11 nov, 2025', deliveryTime = '12:50 pm', }) {
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-white rounded-3xl shadow-sm p-6", children: [_jsx("h3", { className: "text-xl font-bold text-[#262626] mb-4", children: "Pago" }), _jsxs("div", { className: "flex items-center gap-4 p-4 bg-[#FDDF65] rounded-xl", children: [_jsx("div", { className: "flex items-center justify-center w-12 h-12 bg-white rounded-full", children: _jsx(CreditCard, { className: "w-6 h-6 text-[#262626]" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "font-semibold text-[#262626]", children: selectedPaymentMethod }), paymentDetails && (_jsx("p", { className: "text-sm text-[#262626]", children: paymentDetails }))] })] })] }), _jsxs("div", { className: "bg-white rounded-3xl shadow-sm p-6", children: [_jsx("h3", { className: "text-xl font-bold text-[#262626] mb-4", children: "Punto de recogida" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "flex items-center justify-center w-10 h-10 bg-[#FDDF65] rounded-full flex-shrink-0", children: _jsx(MapPin, { className: "w-5 h-5 text-[#262626]" }) }), _jsxs("div", { children: [_jsx("p", { className: "font-semibold text-[#262626] mb-1", children: selectedPickupMethod }), _jsx("p", { className: "text-sm text-gray-600", children: pickupLocation })] })] }), _jsx("div", { className: "w-full h-32 bg-[#E8D9C4] rounded-xl overflow-hidden relative", children: _jsx("div", { className: "absolute inset-0 flex items-center justify-center", children: _jsx(MapPin, { className: "w-8 h-8 text-[#262626] opacity-30" }) }) })] })] }), _jsxs("div", { className: "bg-white rounded-3xl shadow-sm p-6", children: [_jsx("h3", { className: "text-xl font-bold text-[#262626] mb-4", children: "Hora de entrega" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Clock, { className: "w-5 h-5 text-[#5AC7E1]" }), _jsx("span", { className: "text-sm text-gray-600", children: "Hora de entrega programada:" })] }), _jsxs("span", { className: "font-semibold text-[#262626]", children: [deliveryTime, " ", deliveryDate] })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Clock, { className: "w-5 h-5 text-[#5AC7E1]" }), _jsx("span", { className: "text-sm text-gray-600", children: "Hora de entrega esperada:" })] }), _jsxs("span", { className: "font-semibold text-[#262626]", children: [deliveryTime, " ", deliveryDate] })] })] })] })] }));
}
